### ISSUE TITLE
XML 地图错误生成 md 结尾的链接

### ISSUE THREAD

**Issue by BH4HPA** [ENDsoft233/51book#12]
因为 VuePress 生成的链接以 md 结尾，只有在跳转时才会重定向，导致抓取首页内链时抓取到了返回值为 404 的页面链接。

**Comment by ENDsoft233** [comment]
https://github.com/ENDsoft233/51book/blob/fc34553df44b83e196aba6904b981cb49ed4aca5/add_sitemap.js

**Comment by BH4HPA** [comment]
Will fix in https://github.com/ENDsoft233/51book/blob/fc34553df44b83e196aba6904b981cb49ed4aca5/add_sitemap.js#L9

**Comment by BH4HPA** [comment]
![image.png](https://i.loli.net/2021/07/31/kTjFWgQO4vI3nMD.png)

![image.png](https://i.loli.net/2021/07/31/4BfXnqDmK3hxCtd.png)

![image.png](https://i.loli.net/2021/07/31/XjJpHglt96bWz5w.png)
